// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_uiScreenSleep.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_scenes_clear_day_png);   // assets/scenes/clear_day.png
LV_IMG_DECLARE( ui_img_weather_day_png);   // assets/weather/day.png
LV_IMG_DECLARE( ui_img_scenes_clear_night_png);   // assets/scenes/clear_night.png
LV_IMG_DECLARE( ui_img_scenes_cloud_day_png);   // assets/scenes/cloud_day.png
LV_IMG_DECLARE( ui_img_scenes_cloud_night_png);   // assets/scenes/cloud_night.png
LV_IMG_DECLARE( ui_img_scenes_rain_day_png);   // assets/scenes/rain_day.png
LV_IMG_DECLARE( ui_img_scenes_rain_night_png);   // assets/scenes/rain_night.png
LV_IMG_DECLARE( ui_img_scenes_snow_day_png);   // assets/scenes/snow_day.png
LV_IMG_DECLARE( ui_img_scenes_snow_night_png);   // assets/scenes/snow_night.png
LV_IMG_DECLARE( ui_img_scenes_thunderstorm_png);   // assets/scenes/thunderstorm.png
LV_IMG_DECLARE( ui_img_weather_day_cloud_png);   // assets/weather/day_cloud.png
LV_IMG_DECLARE( ui_img_weather_day_fog_png);   // assets/weather/day_fog.png
LV_IMG_DECLARE( ui_img_weather_day_rain_png);   // assets/weather/day_rain.png
LV_IMG_DECLARE( ui_img_weather_day_snow_png);   // assets/weather/day_snow.png
LV_IMG_DECLARE( ui_img_weather_night_png);   // assets/weather/night.png
LV_IMG_DECLARE( ui_img_weather_night_cloud_png);   // assets/weather/night_cloud.png
LV_IMG_DECLARE( ui_img_weather_night_fog_png);   // assets/weather/night_fog.png
LV_IMG_DECLARE( ui_img_weather_night_rain_png);   // assets/weather/night_rain.png
LV_IMG_DECLARE( ui_img_weather_night_snow_png);   // assets/weather/night_snow.png
LV_IMG_DECLARE( ui_img_weather_thunder_storm_png);   // assets/weather/thunder_storm.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
