// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_UISCREENSLEEP_H
#define UI_UISCREENSLEEP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_uiScreenSleep
extern void ui_uiScreenSleep_screen_init(void);
extern void ui_uiScreenSleep_screen_destroy(void);
extern lv_obj_t *ui_uiScreenSleep;
extern lv_obj_t *ui_uiImgBg;
extern lv_obj_t *ui_uiLabelDate;
extern lv_obj_t *ui_uiLabelTime;
extern lv_obj_t *ui_uiLabelCity;
extern lv_obj_t *ui_uiPanelAlertsLabel;
extern lv_obj_t *ui_uiLabelTemp;
extern lv_obj_t *ui_uiLabelWeather;
extern lv_obj_t *ui_uiIconWifi;
extern lv_obj_t *ui_uiIconMqtt;
extern lv_obj_t *ui_uiIconBat;
extern lv_obj_t *ui_uiIconWeather;
// CUSTOM VARIABLES
extern lv_obj_t *uic_uiScreenSleep;
extern lv_obj_t *uic_uiIconWeather;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

