// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_uiIconWeather;
lv_obj_t *uic_uiScreenSleep;
lv_obj_t *ui_uiScreenSleep = NULL;lv_obj_t *ui_uiImgBg = NULL;lv_obj_t *ui_uiIconWeather = NULL;lv_obj_t *ui_uiLabelDate = NULL;lv_obj_t *ui_uiLabelTime = NULL;lv_obj_t *ui_uiLabelCity = NULL;lv_obj_t *ui_uiPanelAlertsLabel = NULL;lv_obj_t *ui_uiLabelTemp = NULL;lv_obj_t *ui_uiLabelWeather = NULL;lv_obj_t *ui_uiIconWifi = NULL;lv_obj_t *ui_uiIconMqtt = NULL;lv_obj_t *ui_uiIconBat = NULL;
// event funtions

// build funtions

void ui_uiScreenSleep_screen_init(void)
{
ui_uiScreenSleep = lv_obj_create(NULL);
lv_obj_remove_flag( ui_uiScreenSleep, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_bg_color(ui_uiScreenSleep, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_uiScreenSleep, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiImgBg = lv_image_create(ui_uiScreenSleep);
lv_image_set_src(ui_uiImgBg, &ui_img_scenes_clear_day_png);
lv_obj_set_width( ui_uiImgBg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiImgBg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_uiImgBg, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_uiImgBg, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_image_set_scale(ui_uiImgBg,255);
lv_obj_set_scrollbar_mode(ui_uiImgBg, LV_SCROLLBAR_MODE_OFF);

ui_uiIconWeather = lv_obj_create(ui_uiScreenSleep);
lv_obj_remove_style_all(ui_uiIconWeather);
lv_obj_set_width( ui_uiIconWeather, 128);
lv_obj_set_height( ui_uiIconWeather, 128);
lv_obj_set_x( ui_uiIconWeather, 30 );
lv_obj_set_y( ui_uiIconWeather, 50 );
lv_obj_remove_flag( ui_uiIconWeather, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_image_src( ui_uiIconWeather, &ui_img_weather_day_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_uiLabelDate = lv_label_create(ui_uiScreenSleep);
lv_obj_set_width( ui_uiLabelDate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelDate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelDate, -30 );
lv_obj_set_y( ui_uiLabelDate, 50 );
lv_obj_set_align( ui_uiLabelDate, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_uiLabelDate,"1 Jan");
lv_obj_set_style_text_font(ui_uiLabelDate, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiLabelTime = lv_label_create(ui_uiScreenSleep);
lv_obj_set_width( ui_uiLabelTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelTime, -110 );
lv_obj_set_y( ui_uiLabelTime, 75 );
lv_obj_set_align( ui_uiLabelTime, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_uiLabelTime,"12:00");
lv_obj_set_style_text_font(ui_uiLabelTime, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_uiLabelTime, 500, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiLabelCity = lv_label_create(ui_uiScreenSleep);
lv_obj_set_width( ui_uiLabelCity, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelCity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelCity, -30 );
lv_obj_set_y( ui_uiLabelCity, -80 );
lv_obj_set_align( ui_uiLabelCity, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_uiLabelCity,"No City");
lv_obj_set_style_text_decor(ui_uiLabelCity, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiLabelCity, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiPanelAlertsLabel = lv_label_create(ui_uiScreenSleep);
lv_obj_set_width( ui_uiPanelAlertsLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiPanelAlertsLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiPanelAlertsLabel, -30 );
lv_obj_set_y( ui_uiPanelAlertsLabel, -120 );
lv_obj_set_align( ui_uiPanelAlertsLabel, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_uiPanelAlertsLabel,"0 Alerts");
lv_obj_remove_flag( ui_uiPanelAlertsLabel, LV_OBJ_FLAG_CLICK_FOCUSABLE );    /// Flags
lv_obj_set_style_text_color(ui_uiPanelAlertsLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiPanelAlertsLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiPanelAlertsLabel, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiLabelTemp = lv_label_create(ui_uiScreenSleep);
lv_obj_set_width( ui_uiLabelTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelTemp, 30 );
lv_obj_set_y( ui_uiLabelTemp, 85 );
lv_obj_set_align( ui_uiLabelTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_uiLabelTemp,"--°C");
lv_obj_set_style_text_font(ui_uiLabelTemp, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_uiLabelTemp, 400, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiLabelWeather = lv_label_create(ui_uiScreenSleep);
lv_obj_set_width( ui_uiLabelWeather, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelWeather, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelWeather, 30 );
lv_obj_set_y( ui_uiLabelWeather, -50 );
lv_obj_set_align( ui_uiLabelWeather, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_uiLabelWeather,"No Data");
lv_obj_set_style_text_font(ui_uiLabelWeather, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_uiLabelWeather, 200, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiIconWifi = lv_label_create(ui_uiScreenSleep);
lv_obj_set_width( ui_uiIconWifi, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiIconWifi, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiIconWifi, -105 );
lv_obj_set_y( ui_uiIconWifi, -51 );
lv_obj_set_align( ui_uiIconWifi, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_uiIconWifi,"");
lv_obj_set_style_text_font(ui_uiIconWifi, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiIconMqtt = lv_label_create(ui_uiScreenSleep);
lv_obj_set_width( ui_uiIconMqtt, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiIconMqtt, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiIconMqtt, -70 );
lv_obj_set_y( ui_uiIconMqtt, -50 );
lv_obj_set_align( ui_uiIconMqtt, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_uiIconMqtt,"");
lv_obj_set_style_text_font(ui_uiIconMqtt, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiIconBat = lv_label_create(ui_uiScreenSleep);
lv_obj_set_width( ui_uiIconBat, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiIconBat, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiIconBat, -30 );
lv_obj_set_y( ui_uiIconBat, -51 );
lv_obj_set_align( ui_uiIconBat, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_uiIconBat,"");
lv_obj_set_style_text_font(ui_uiIconBat, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_uiIconBat, 300, LV_PART_MAIN| LV_STATE_DEFAULT);

uic_uiScreenSleep = ui_uiScreenSleep;
uic_uiIconWeather = ui_uiIconWeather;

}

void ui_uiScreenSleep_screen_destroy(void)
{
   if (ui_uiScreenSleep) lv_obj_del(ui_uiScreenSleep);

// NULL screen variables
uic_uiScreenSleep= NULL;
ui_uiScreenSleep= NULL;
ui_uiImgBg= NULL;
uic_uiIconWeather= NULL;
ui_uiIconWeather= NULL;
ui_uiLabelDate= NULL;
ui_uiLabelTime= NULL;
ui_uiLabelCity= NULL;
ui_uiPanelAlertsLabel= NULL;
ui_uiLabelTemp= NULL;
ui_uiLabelWeather= NULL;
ui_uiIconWifi= NULL;
ui_uiIconMqtt= NULL;
ui_uiIconBat= NULL;

}
