// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_HomeScreen.h"
#include "ui_SleepScreen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_bg_bg6rc2_png);   // assets/bg/bg6rc2.png
LV_IMG_DECLARE( ui_img_253037777);   // assets/ha-icons/lightbulb.png
LV_IMG_DECLARE( ui_img_scenes_clear_day_png);   // assets/scenes/clear_day.png
LV_IMG_DECLARE( ui_img_weather_day_png);   // assets/weather/day.png
LV_IMG_DECLARE( ui_img_bg_bg3rc2_png);   // assets/bg/bg3rc2.png
LV_IMG_DECLARE( ui_img_133537992);   // assets/ha-icons/ac.png
LV_IMG_DECLARE( ui_img_827440816);   // assets/ha-icons/dryer.png
LV_IMG_DECLARE( ui_img_1332138075);   // assets/ha-icons/fan.png
LV_IMG_DECLARE( ui_img_175529197);   // assets/ha-icons/garage.png
LV_IMG_DECLARE( ui_img_979047894);   // assets/ha-icons/radiator.png
LV_IMG_DECLARE( ui_img_450969811);   // assets/ha-icons/socket.png
LV_IMG_DECLARE( ui_img_285837919);   // assets/ha-icons/speaker.png
LV_IMG_DECLARE( ui_img_252433816);   // assets/ha-icons/switch.png
LV_IMG_DECLARE( ui_img_435491338);   // assets/ha-icons/tv.png
LV_IMG_DECLARE( ui_img_1965837174);   // assets/ha-icons/washmachine.png
LV_IMG_DECLARE( ui_img_scenes_clear_night_png);   // assets/scenes/clear_night.png
LV_IMG_DECLARE( ui_img_scenes_cloud_day_png);   // assets/scenes/cloud_day.png
LV_IMG_DECLARE( ui_img_scenes_cloud_night_png);   // assets/scenes/cloud_night.png
LV_IMG_DECLARE( ui_img_scenes_rain_day_png);   // assets/scenes/rain_day.png
LV_IMG_DECLARE( ui_img_scenes_rain_night_png);   // assets/scenes/rain_night.png
LV_IMG_DECLARE( ui_img_scenes_snow_day_png);   // assets/scenes/snow_day.png
LV_IMG_DECLARE( ui_img_scenes_snow_night_png);   // assets/scenes/snow_night.png
LV_IMG_DECLARE( ui_img_scenes_thunderstorm_png);   // assets/scenes/thunderstorm.png
LV_IMG_DECLARE( ui_img_weather_day_cloud_png);   // assets/weather/day_cloud.png
LV_IMG_DECLARE( ui_img_weather_day_fog_png);   // assets/weather/day_fog.png
LV_IMG_DECLARE( ui_img_weather_day_rain_png);   // assets/weather/day_rain.png
LV_IMG_DECLARE( ui_img_weather_day_snow_png);   // assets/weather/day_snow.png
LV_IMG_DECLARE( ui_img_weather_night_png);   // assets/weather/night.png
LV_IMG_DECLARE( ui_img_weather_night_cloud_png);   // assets/weather/night_cloud.png
LV_IMG_DECLARE( ui_img_weather_night_fog_png);   // assets/weather/night_fog.png
LV_IMG_DECLARE( ui_img_weather_night_rain_png);   // assets/weather/night_rain.png
LV_IMG_DECLARE( ui_img_weather_night_snow_png);   // assets/weather/night_snow.png
LV_IMG_DECLARE( ui_img_weather_thunder_storm_png);   // assets/weather/thunder_storm.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
