// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomeScreen
extern void ui_HomeScreen_screen_init(void);
extern void ui_HomeScreen_screen_destroy(void);
extern lv_obj_t *ui_HomeScreen;
extern lv_obj_t *ui_baseP;
extern lv_obj_t *ui_topP;
extern lv_obj_t *ui_rmPe;
extern lv_obj_t *ui_rmTa;
extern lv_obj_t *ui_rmC;
extern lv_obj_t *ui_CompRoom;
extern lv_obj_t *ui_tdC;
extern lv_obj_t *ui_Time;
extern lv_obj_t *ui_temp;
extern lv_obj_t *ui_loc;
extern lv_obj_t *ui_cli;
extern lv_obj_t *ui_date;
extern lv_obj_t *ui_stC;
extern lv_obj_t *ui_wifi;
extern lv_obj_t *ui_mqtt;
extern lv_obj_t *ui_batt;
extern lv_obj_t *ui_bell;
extern lv_obj_t *ui_haswCnd;
extern lv_obj_t *ui_noData1;
extern lv_obj_t *ui_haswC;
extern lv_obj_t *ui_CompSwitch;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

