// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_SleepScreen = NULL;lv_obj_t *ui_ImgBg = NULL;lv_obj_t *ui_IconWeather = NULL;lv_obj_t *ui_LabelDate = NULL;lv_obj_t *ui_LabelTime = NULL;lv_obj_t *ui_LabelCity = NULL;lv_obj_t *ui_AlertsLabel = NULL;lv_obj_t *ui_LabelTemp = NULL;lv_obj_t *ui_LabelWeather = NULL;lv_obj_t *ui_IconMqtt = NULL;lv_obj_t *ui_IconWifi = NULL;lv_obj_t *ui_IconBat = NULL;
// event funtions

// build funtions

void ui_SleepScreen_screen_init(void)
{
ui_SleepScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SleepScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SleepScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SleepScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgBg = lv_img_create(ui_SleepScreen);
lv_img_set_src(ui_ImgBg, &ui_img_scenes_clear_day_png);
lv_obj_set_width( ui_ImgBg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImgBg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ImgBg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImgBg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImgBg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_IconWeather = lv_img_create(ui_SleepScreen);
lv_img_set_src(ui_IconWeather, &ui_img_weather_day_png);
lv_obj_set_width( ui_IconWeather, 128);
lv_obj_set_height( ui_IconWeather, 128);
lv_obj_set_x( ui_IconWeather, 30 );
lv_obj_set_y( ui_IconWeather, 50 );
lv_obj_add_flag( ui_IconWeather, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_IconWeather, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelDate = lv_label_create(ui_SleepScreen);
lv_obj_set_width( ui_LabelDate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelDate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelDate, -30 );
lv_obj_set_y( ui_LabelDate, 50 );
lv_obj_set_align( ui_LabelDate, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_LabelDate,"1 Jan");
lv_obj_set_style_text_color(ui_LabelDate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelDate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelDate, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelTime = lv_label_create(ui_SleepScreen);
lv_obj_set_width( ui_LabelTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelTime, -110 );
lv_obj_set_y( ui_LabelTime, 75 );
lv_obj_set_align( ui_LabelTime, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_LabelTime,"12:00");
lv_obj_set_style_text_color(ui_LabelTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelTime, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_zoom(ui_LabelTime, 500, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelCity = lv_label_create(ui_SleepScreen);
lv_obj_set_width( ui_LabelCity, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelCity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelCity, -30 );
lv_obj_set_y( ui_LabelCity, -80 );
lv_obj_set_align( ui_LabelCity, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_LabelCity,"No City");
lv_obj_set_style_text_color(ui_LabelCity, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelCity, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelCity, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AlertsLabel = lv_label_create(ui_SleepScreen);
lv_obj_set_width( ui_AlertsLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AlertsLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AlertsLabel, -30 );
lv_obj_set_y( ui_AlertsLabel, -120 );
lv_obj_set_align( ui_AlertsLabel, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_AlertsLabel,"0 Alerts");
lv_obj_set_style_text_color(ui_AlertsLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AlertsLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AlertsLabel, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelTemp = lv_label_create(ui_SleepScreen);
lv_obj_set_width( ui_LabelTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelTemp, 30 );
lv_obj_set_y( ui_LabelTemp, 80 );
lv_obj_set_align( ui_LabelTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_LabelTemp,"--°");
lv_obj_set_style_text_color(ui_LabelTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelTemp, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_zoom(ui_LabelTemp, 400, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelWeather = lv_label_create(ui_SleepScreen);
lv_obj_set_width( ui_LabelWeather, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelWeather, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelWeather, 30 );
lv_obj_set_y( ui_LabelWeather, -50 );
lv_obj_set_align( ui_LabelWeather, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_LabelWeather,"No Data");
lv_obj_set_style_text_color(ui_LabelWeather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelWeather, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelWeather, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_LabelWeather, 200, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_IconMqtt = lv_label_create(ui_SleepScreen);
lv_obj_set_width( ui_IconMqtt, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_IconMqtt, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_IconMqtt, -70 );
lv_obj_set_y( ui_IconMqtt, -50 );
lv_obj_set_align( ui_IconMqtt, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_IconMqtt,"");
lv_obj_set_style_text_color(ui_IconMqtt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_IconMqtt, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_IconMqtt, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_IconWifi = lv_label_create(ui_SleepScreen);
lv_obj_set_width( ui_IconWifi, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_IconWifi, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_IconWifi, -105 );
lv_obj_set_y( ui_IconWifi, -50 );
lv_obj_set_align( ui_IconWifi, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_IconWifi,"");
lv_obj_set_style_text_color(ui_IconWifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_IconWifi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_IconWifi, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_IconBat = lv_label_create(ui_SleepScreen);
lv_obj_set_width( ui_IconBat, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_IconBat, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_IconBat, -30 );
lv_obj_set_y( ui_IconBat, -51 );
lv_obj_set_align( ui_IconBat, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_IconBat,"");
lv_obj_set_style_text_color(ui_IconBat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_IconBat, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_IconBat, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_zoom(ui_IconBat, 300, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_SleepScreen_screen_destroy(void)
{
   if (ui_SleepScreen) lv_obj_del(ui_SleepScreen);

// NULL screen variables
ui_SleepScreen= NULL;
ui_ImgBg= NULL;
ui_IconWeather= NULL;
ui_LabelDate= NULL;
ui_LabelTime= NULL;
ui_LabelCity= NULL;
ui_AlertsLabel= NULL;
ui_LabelTemp= NULL;
ui_LabelWeather= NULL;
ui_IconMqtt= NULL;
ui_IconWifi= NULL;
ui_IconBat= NULL;

}
