// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_HAScreen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_bg_bg6rc2_png);   // assets/bg/bg6rc2.png
LV_IMG_DECLARE( ui_img_253037777);   // assets/ha-icons/lightbulb.png
LV_IMG_DECLARE( ui_img_133537992);   // assets/ha-icons/ac.png
LV_IMG_DECLARE( ui_img_1332138075);   // assets/ha-icons/fan.png
LV_IMG_DECLARE( ui_img_435491338);   // assets/ha-icons/tv.png
LV_IMG_DECLARE( ui_img_252433816);   // assets/ha-icons/switch.png
LV_IMG_DECLARE( ui_img_1965837174);   // assets/ha-icons/washmachine.png
LV_IMG_DECLARE( ui_img_827440816);   // assets/ha-icons/dryer.png
LV_IMG_DECLARE( ui_img_175529197);   // assets/ha-icons/garage.png
LV_IMG_DECLARE( ui_img_979047894);   // assets/ha-icons/radiator.png
LV_IMG_DECLARE( ui_img_450969811);   // assets/ha-icons/socket.png
LV_IMG_DECLARE( ui_img_285837919);   // assets/ha-icons/speaker.png
LV_IMG_DECLARE( ui_img_bg_bg3rc2_png);   // assets/bg/bg3rc2.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
