// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT CompSwitch

lv_obj_t *ui_CompSwitch_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_CompSwitch;
cui_CompSwitch = lv_obj_create(comp_parent);
lv_obj_remove_style_all(cui_CompSwitch);
lv_obj_set_width( cui_CompSwitch, 205);
lv_obj_set_height( cui_CompSwitch, 70);
lv_obj_set_x( cui_CompSwitch, 1 );
lv_obj_set_y( cui_CompSwitch, 1 );
lv_obj_clear_flag( cui_CompSwitch, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_CompSwitch, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_CompSwitch, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_CompSwitch, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_icc1;
cui_icc1 = lv_obj_create(cui_CompSwitch);
lv_obj_remove_style_all(cui_icc1);
lv_obj_set_width( cui_icc1, 50);
lv_obj_set_height( cui_icc1, 50);
lv_obj_set_x( cui_icc1, 10 );
lv_obj_set_y( cui_icc1, 0 );
lv_obj_set_align( cui_icc1, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( cui_icc1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_icc1, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_icc1, lv_color_hex(0xFEC106), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_icc1, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_icp1;
cui_icp1 = lv_obj_create(cui_icc1);
lv_obj_set_width( cui_icp1, 32);
lv_obj_set_height( cui_icp1, 32);
lv_obj_set_align( cui_icp1, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_icp1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_icp1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_icp1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( cui_icp1, &ui_img_253037777, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_recolor(cui_icp1, lv_color_hex(0xFEC106), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(cui_icp1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_swn1;
cui_swn1 = lv_label_create(cui_CompSwitch);
lv_obj_set_width( cui_swn1, 125);
lv_obj_set_height( cui_swn1, 20);
lv_obj_set_x( cui_swn1, -10 );
lv_obj_set_y( cui_swn1, -5 );
lv_obj_set_align( cui_swn1, LV_ALIGN_RIGHT_MID );
lv_label_set_text(cui_swn1,"Lights");
lv_obj_set_style_text_color(cui_swn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_swn1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(cui_swn1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_swn1, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_swn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_swn1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_rm1;
cui_rm1 = lv_label_create(cui_CompSwitch);
lv_obj_set_width( cui_rm1, 125);
lv_obj_set_height( cui_rm1, 16);
lv_obj_set_x( cui_rm1, -10 );
lv_obj_set_y( cui_rm1, -14 );
lv_obj_set_align( cui_rm1, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(cui_rm1,"Master BedRoom");
lv_obj_set_style_text_color(cui_rm1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_rm1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(cui_rm1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_rm1, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_rm1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_rm1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_COMPSWITCH_NUM);
children[UI_COMP_COMPSWITCH_COMPSWITCH] = cui_CompSwitch;
children[UI_COMP_COMPSWITCH_ICC1] = cui_icc1;
children[UI_COMP_COMPSWITCH_ICC1_ICP1] = cui_icp1;
children[UI_COMP_COMPSWITCH_SWN1] = cui_swn1;
children[UI_COMP_COMPSWITCH_RM1] = cui_rm1;
lv_obj_add_event_cb(cui_CompSwitch, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_CompSwitch, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_CompSwitch_create_hook(cui_CompSwitch);
return cui_CompSwitch; 
}

