// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_HAScreen = NULL;lv_obj_t *ui_baseP = NULL;lv_obj_t *ui_topP = NULL;lv_obj_t *ui_rmC = NULL;lv_obj_t *ui_rmP1 = NULL;lv_obj_t *ui_rmT1 = NULL;lv_obj_t *ui_rmP2 = NULL;lv_obj_t *ui_rmT2 = NULL;lv_obj_t *ui_rmP3 = NULL;lv_obj_t *ui_rmT3 = NULL;lv_obj_t *ui_rmPe = NULL;lv_obj_t *ui_rmTa = NULL;lv_obj_t *ui_tdC = NULL;lv_obj_t *ui_Time = NULL;lv_obj_t *ui_temp = NULL;lv_obj_t *ui_loc = NULL;lv_obj_t *ui_cli = NULL;lv_obj_t *ui_date = NULL;lv_obj_t *ui_stC = NULL;lv_obj_t *ui_wifi = NULL;lv_obj_t *ui_mqtt = NULL;lv_obj_t *ui_batt = NULL;lv_obj_t *ui_bell = NULL;lv_obj_t *ui_haswCnd = NULL;lv_obj_t *ui_noData1 = NULL;lv_obj_t *ui_haswC = NULL;lv_obj_t *ui_CompSwitch = NULL;
// event funtions

// build funtions

void ui_HAScreen_screen_init(void)
{
ui_HAScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_HAScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_baseP = lv_obj_create(ui_HAScreen);
lv_obj_set_width( ui_baseP, 480);
lv_obj_set_height( ui_baseP, 480);
lv_obj_set_align( ui_baseP, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_baseP,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_baseP, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_baseP, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_baseP, &ui_img_bg_bg6rc2_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_topP = lv_obj_create(ui_HAScreen);
lv_obj_set_width( ui_topP, 445);
lv_obj_set_height( ui_topP, 445);
lv_obj_set_align( ui_topP, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_topP, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_topP, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_topP, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_topP, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_topP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_topP, 80, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_topP, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_topP, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_topP, 85, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_topP, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_topP, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_topP, 60, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rmC = lv_obj_create(ui_HAScreen);
lv_obj_remove_style_all(ui_rmC);
lv_obj_set_width( ui_rmC, 420);
lv_obj_set_height( ui_rmC, 30);
lv_obj_set_x( ui_rmC, 0 );
lv_obj_set_y( ui_rmC, 35 );
lv_obj_set_align( ui_rmC, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_rmC, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_rmP1 = lv_obj_create(ui_rmC);
lv_obj_set_width( ui_rmP1, 110);
lv_obj_set_height( ui_rmP1, 30);
lv_obj_set_align( ui_rmP1, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_rmP1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_rmP1, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_rmP1, lv_color_hex(0x28A0FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_rmP1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rmT1 = lv_label_create(ui_rmP1);
lv_obj_set_width( ui_rmT1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_rmT1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_rmT1, LV_ALIGN_CENTER );
lv_label_set_text(ui_rmT1,"Living Room");
lv_obj_set_style_text_color(ui_rmT1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_rmT1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_rmT1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_rmT1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rmP2 = lv_obj_create(ui_rmC);
lv_obj_set_width( ui_rmP2, 110);
lv_obj_set_height( ui_rmP2, 30);
lv_obj_set_x( ui_rmP2, -35 );
lv_obj_set_y( ui_rmP2, 0 );
lv_obj_set_align( ui_rmP2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_rmP2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_rmP2, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_rmP2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_rmP2, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rmT2 = lv_label_create(ui_rmP2);
lv_obj_set_width( ui_rmT2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_rmT2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_rmT2, LV_ALIGN_CENTER );
lv_label_set_text(ui_rmT2,"Dining Room");
lv_obj_set_style_text_color(ui_rmT2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_rmT2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_rmT2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_rmT2, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rmP3 = lv_obj_create(ui_rmC);
lv_obj_set_width( ui_rmP3, 140);
lv_obj_set_height( ui_rmP3, 30);
lv_obj_set_x( ui_rmP3, -40 );
lv_obj_set_y( ui_rmP3, 0 );
lv_obj_set_align( ui_rmP3, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_rmP3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_rmP3, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_rmP3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_rmP3, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rmT3 = lv_label_create(ui_rmP3);
lv_obj_set_width( ui_rmT3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_rmT3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_rmT3, LV_ALIGN_CENTER );
lv_label_set_text(ui_rmT3,"Master BedRoom");
lv_obj_set_style_text_color(ui_rmT3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_rmT3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_rmT3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_rmT3, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rmPe = lv_obj_create(ui_rmC);
lv_obj_set_width( ui_rmPe, 30);
lv_obj_set_height( ui_rmPe, 30);
lv_obj_set_align( ui_rmPe, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_rmPe, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_rmPe, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_rmPe, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_rmPe, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rmTa = lv_label_create(ui_rmPe);
lv_obj_set_width( ui_rmTa, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_rmTa, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_rmTa, LV_ALIGN_CENTER );
lv_label_set_text(ui_rmTa,"");
lv_obj_set_style_text_color(ui_rmTa, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_rmTa, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_rmTa, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_rmTa, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tdC = lv_obj_create(ui_HAScreen);
lv_obj_remove_style_all(ui_tdC);
lv_obj_set_width( ui_tdC, 280);
lv_obj_set_height( ui_tdC, 120);
lv_obj_set_x( ui_tdC, 30 );
lv_obj_set_y( ui_tdC, 80 );
lv_obj_clear_flag( ui_tdC, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_tdC, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_tdC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_tdC, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Time = lv_label_create(ui_tdC);
lv_obj_set_width( ui_Time, 150);
lv_obj_set_height( ui_Time, 50);
lv_obj_set_x( ui_Time, -10 );
lv_obj_set_y( ui_Time, 5 );
lv_obj_set_align( ui_Time, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_Time,"00:00");
lv_obj_set_style_text_color(ui_Time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Time, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Time, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Time, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Time, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_temp = lv_label_create(ui_tdC);
lv_obj_set_width( ui_temp, 90);
lv_obj_set_height( ui_temp, 50);
lv_obj_set_x( ui_temp, 15 );
lv_obj_set_y( ui_temp, -10 );
lv_obj_set_align( ui_temp, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_temp,"88°");
lv_obj_set_style_text_color(ui_temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_temp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_temp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_temp, &lv_font_montserrat_46, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_temp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_loc = lv_label_create(ui_tdC);
lv_obj_set_width( ui_loc, 160);
lv_obj_set_height( ui_loc, 20);
lv_obj_set_x( ui_loc, -10 );
lv_obj_set_y( ui_loc, 10 );
lv_obj_set_align( ui_loc, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_loc,"Hyderabad");
lv_obj_set_style_text_color(ui_loc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_loc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_loc, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_loc, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_loc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_loc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_cli = lv_label_create(ui_tdC);
lv_obj_set_width( ui_cli, 160);
lv_obj_set_height( ui_cli, 25);
lv_obj_set_x( ui_cli, -10 );
lv_obj_set_y( ui_cli, -10 );
lv_obj_set_align( ui_cli, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_cli,"Freezing Drizzle");
lv_obj_set_style_text_color(ui_cli, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_cli, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_cli, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_cli, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_cli, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_cli, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_date = lv_label_create(ui_tdC);
lv_obj_set_width( ui_date, 80);
lv_obj_set_height( ui_date, 25);
lv_obj_set_x( ui_date, 15 );
lv_obj_set_y( ui_date, 20 );
lv_label_set_text(ui_date,"22 Oct");
lv_obj_set_style_text_color(ui_date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_date, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_date, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_date, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_date, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_stC = lv_obj_create(ui_HAScreen);
lv_obj_remove_style_all(ui_stC);
lv_obj_set_width( ui_stC, 130);
lv_obj_set_height( ui_stC, 120);
lv_obj_set_x( ui_stC, -30 );
lv_obj_set_y( ui_stC, 80 );
lv_obj_set_align( ui_stC, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_stC, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_stC, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_stC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_stC, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifi = lv_label_create(ui_stC);
lv_obj_set_width( ui_wifi, 50);
lv_obj_set_height( ui_wifi, 40);
lv_obj_set_x( ui_wifi, -10 );
lv_obj_set_y( ui_wifi, 15 );
lv_obj_set_align( ui_wifi, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_wifi,"");
lv_obj_set_style_text_color(ui_wifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_wifi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_wifi, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_wifi, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_wifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wifi, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mqtt = lv_label_create(ui_stC);
lv_obj_set_width( ui_mqtt, 50);
lv_obj_set_height( ui_mqtt, 40);
lv_obj_set_x( ui_mqtt, 10 );
lv_obj_set_y( ui_mqtt, 15 );
lv_label_set_text(ui_mqtt,"");
lv_obj_set_style_text_color(ui_mqtt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mqtt, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_mqtt, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_mqtt, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_mqtt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mqtt, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batt = lv_label_create(ui_stC);
lv_obj_set_width( ui_batt, 50);
lv_obj_set_height( ui_batt, 40);
lv_obj_set_x( ui_batt, 10 );
lv_obj_set_y( ui_batt, -10 );
lv_obj_set_align( ui_batt, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_batt,"");
lv_obj_set_style_text_color(ui_batt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_batt, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_batt, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_batt, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_batt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batt, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bell = lv_label_create(ui_stC);
lv_obj_set_width( ui_bell, 50);
lv_obj_set_height( ui_bell, 40);
lv_obj_set_x( ui_bell, -10 );
lv_obj_set_y( ui_bell, -10 );
lv_obj_set_align( ui_bell, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_bell,"");
lv_obj_set_style_text_color(ui_bell, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_bell, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_bell, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_bell, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_bell, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_bell, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_haswCnd = lv_obj_create(ui_HAScreen);
lv_obj_remove_style_all(ui_haswCnd);
lv_obj_set_width( ui_haswCnd, 420);
lv_obj_set_height( ui_haswCnd, 230);
lv_obj_set_x( ui_haswCnd, 0 );
lv_obj_set_y( ui_haswCnd, -35 );
lv_obj_set_align( ui_haswCnd, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_haswCnd, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_haswCnd, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_haswCnd, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_haswCnd, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_haswCnd, 100, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_noData1 = lv_label_create(ui_haswCnd);
lv_obj_set_width( ui_noData1, 300);
lv_obj_set_height( ui_noData1, 50);
lv_obj_set_align( ui_noData1, LV_ALIGN_CENTER );
lv_label_set_text(ui_noData1,"No elements data received from HomeAssistant");
lv_obj_set_style_text_color(ui_noData1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_noData1, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_noData1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_noData1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_noData1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_noData1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_haswC = lv_obj_create(ui_HAScreen);
lv_obj_remove_style_all(ui_haswC);
lv_obj_set_width( ui_haswC, 420);
lv_obj_set_height( ui_haswC, 230);
lv_obj_set_x( ui_haswC, 0 );
lv_obj_set_y( ui_haswC, -35 );
lv_obj_set_align( ui_haswC, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_haswC,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_haswC, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_haswC, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_haswC, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_haswC, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CompSwitch = ui_CompSwitch_create(ui_haswC);
lv_obj_set_x( ui_CompSwitch, 1 );
lv_obj_set_y( ui_CompSwitch, 1 );

}

void ui_HAScreen_screen_destroy(void)
{
   if (ui_HAScreen) lv_obj_del(ui_HAScreen);

// NULL screen variables
ui_HAScreen= NULL;
ui_baseP= NULL;
ui_topP= NULL;
ui_rmC= NULL;
ui_rmP1= NULL;
ui_rmT1= NULL;
ui_rmP2= NULL;
ui_rmT2= NULL;
ui_rmP3= NULL;
ui_rmT3= NULL;
ui_rmPe= NULL;
ui_rmTa= NULL;
ui_tdC= NULL;
ui_Time= NULL;
ui_temp= NULL;
ui_loc= NULL;
ui_cli= NULL;
ui_date= NULL;
ui_stC= NULL;
ui_wifi= NULL;
ui_mqtt= NULL;
ui_batt= NULL;
ui_bell= NULL;
ui_haswCnd= NULL;
ui_noData1= NULL;
ui_haswC= NULL;
ui_CompSwitch= NULL;

}
