// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HASCREEN_H
#define UI_HASCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HAScreen
extern void ui_HAScreen_screen_init(void);
extern void ui_HAScreen_screen_destroy(void);
extern lv_obj_t *ui_HAScreen;
extern lv_obj_t *ui_baseP;
extern lv_obj_t *ui_topP;
extern lv_obj_t *ui_rmC;
extern lv_obj_t *ui_rmP1;
extern lv_obj_t *ui_rmT1;
extern lv_obj_t *ui_rmP2;
extern lv_obj_t *ui_rmT2;
extern lv_obj_t *ui_rmP3;
extern lv_obj_t *ui_rmT3;
extern lv_obj_t *ui_rmPe;
extern lv_obj_t *ui_rmTa;
extern lv_obj_t *ui_tdC;
extern lv_obj_t *ui_time;
extern lv_obj_t *ui_temp;
extern lv_obj_t *ui_loc;
extern lv_obj_t *ui_cli;
extern lv_obj_t *ui_date;
extern lv_obj_t *ui_stC;
extern lv_obj_t *ui_wifi;
extern lv_obj_t *ui_mqtt;
extern lv_obj_t *ui_batt;
extern lv_obj_t *ui_bell;
extern lv_obj_t *ui_haswCnd;
extern lv_obj_t *ui_noData;
extern lv_obj_t *ui_haswC;
extern lv_obj_t *ui_sw1;
extern lv_obj_t *ui_icc1;
extern lv_obj_t *ui_icp1;
extern lv_obj_t *ui_swn1;
extern lv_obj_t *ui_rm1;
extern lv_obj_t *ui_sw2;
extern lv_obj_t *ui_icc2;
extern lv_obj_t *ui_icp2;
extern lv_obj_t *ui_swn2;
extern lv_obj_t *ui_rm2;
extern lv_obj_t *ui_sw3;
extern lv_obj_t *ui_icc3;
extern lv_obj_t *ui_icp3;
extern lv_obj_t *ui_swn3;
extern lv_obj_t *ui_rm3;
extern lv_obj_t *ui_sw4;
extern lv_obj_t *ui_icc4;
extern lv_obj_t *ui_icp4;
extern lv_obj_t *ui_swn4;
extern lv_obj_t *ui_rm4;
extern lv_obj_t *ui_sw5;
extern lv_obj_t *ui_icc5;
extern lv_obj_t *ui_icp5;
extern lv_obj_t *ui_swn5;
extern lv_obj_t *ui_rm5;
extern lv_obj_t *ui_sw6;
extern lv_obj_t *ui_icc6;
extern lv_obj_t *ui_icp6;
extern lv_obj_t *ui_swn6;
extern lv_obj_t *ui_rm6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

