// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_HAScreen = NULL;lv_obj_t *ui_baseP = NULL;lv_obj_t *ui_topP = NULL;lv_obj_t *ui_rmC = NULL;lv_obj_t *ui_rmP1 = NULL;lv_obj_t *ui_rmT1 = NULL;lv_obj_t *ui_rmP2 = NULL;lv_obj_t *ui_rmT2 = NULL;lv_obj_t *ui_rmP3 = NULL;lv_obj_t *ui_rmT3 = NULL;lv_obj_t *ui_rmPe = NULL;lv_obj_t *ui_rmTa = NULL;lv_obj_t *ui_tdC = NULL;lv_obj_t *ui_time = NULL;lv_obj_t *ui_temp = NULL;lv_obj_t *ui_loc = NULL;lv_obj_t *ui_cli = NULL;lv_obj_t *ui_date = NULL;lv_obj_t *ui_stC = NULL;lv_obj_t *ui_wifi = NULL;lv_obj_t *ui_mqtt = NULL;lv_obj_t *ui_batt = NULL;lv_obj_t *ui_bell = NULL;lv_obj_t *ui_haswCnd = NULL;lv_obj_t *ui_noData = NULL;lv_obj_t *ui_haswC = NULL;lv_obj_t *ui_sw1 = NULL;lv_obj_t *ui_icc1 = NULL;lv_obj_t *ui_icp1 = NULL;lv_obj_t *ui_swn1 = NULL;lv_obj_t *ui_rm1 = NULL;lv_obj_t *ui_sw2 = NULL;lv_obj_t *ui_icc2 = NULL;lv_obj_t *ui_icp2 = NULL;lv_obj_t *ui_swn2 = NULL;lv_obj_t *ui_rm2 = NULL;lv_obj_t *ui_sw3 = NULL;lv_obj_t *ui_icc3 = NULL;lv_obj_t *ui_icp3 = NULL;lv_obj_t *ui_swn3 = NULL;lv_obj_t *ui_rm3 = NULL;lv_obj_t *ui_sw4 = NULL;lv_obj_t *ui_icc4 = NULL;lv_obj_t *ui_icp4 = NULL;lv_obj_t *ui_swn4 = NULL;lv_obj_t *ui_rm4 = NULL;lv_obj_t *ui_sw5 = NULL;lv_obj_t *ui_icc5 = NULL;lv_obj_t *ui_icp5 = NULL;lv_obj_t *ui_swn5 = NULL;lv_obj_t *ui_rm5 = NULL;lv_obj_t *ui_sw6 = NULL;lv_obj_t *ui_icc6 = NULL;lv_obj_t *ui_icp6 = NULL;lv_obj_t *ui_swn6 = NULL;lv_obj_t *ui_rm6 = NULL;
// event funtions

// build funtions

void ui_HAScreen_screen_init(void)
{
ui_HAScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_HAScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_baseP = lv_obj_create(ui_HAScreen);
lv_obj_set_width( ui_baseP, 480);
lv_obj_set_height( ui_baseP, 480);
lv_obj_set_align( ui_baseP, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_baseP,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_baseP, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_baseP, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_baseP, &ui_img_bg_bg6rc2_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_topP = lv_obj_create(ui_HAScreen);
lv_obj_set_width( ui_topP, 445);
lv_obj_set_height( ui_topP, 445);
lv_obj_set_align( ui_topP, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_topP, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_topP, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_topP, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_topP, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_topP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_topP, 80, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_topP, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_topP, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_topP, 85, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_topP, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_topP, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_topP, 60, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rmC = lv_obj_create(ui_HAScreen);
lv_obj_remove_style_all(ui_rmC);
lv_obj_set_width( ui_rmC, 420);
lv_obj_set_height( ui_rmC, 30);
lv_obj_set_x( ui_rmC, 0 );
lv_obj_set_y( ui_rmC, 35 );
lv_obj_set_align( ui_rmC, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_rmC, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_rmP1 = lv_obj_create(ui_rmC);
lv_obj_set_width( ui_rmP1, 110);
lv_obj_set_height( ui_rmP1, 30);
lv_obj_set_align( ui_rmP1, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_rmP1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_rmP1, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_rmP1, lv_color_hex(0x28A0FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_rmP1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rmT1 = lv_label_create(ui_rmP1);
lv_obj_set_width( ui_rmT1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_rmT1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_rmT1, LV_ALIGN_CENTER );
lv_label_set_text(ui_rmT1,"Living Room");
lv_obj_set_style_text_color(ui_rmT1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_rmT1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_rmT1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_rmT1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rmP2 = lv_obj_create(ui_rmC);
lv_obj_set_width( ui_rmP2, 110);
lv_obj_set_height( ui_rmP2, 30);
lv_obj_set_x( ui_rmP2, -35 );
lv_obj_set_y( ui_rmP2, 0 );
lv_obj_set_align( ui_rmP2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_rmP2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_rmP2, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_rmP2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_rmP2, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rmT2 = lv_label_create(ui_rmP2);
lv_obj_set_width( ui_rmT2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_rmT2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_rmT2, LV_ALIGN_CENTER );
lv_label_set_text(ui_rmT2,"Dining Room");
lv_obj_set_style_text_color(ui_rmT2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_rmT2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_rmT2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_rmT2, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rmP3 = lv_obj_create(ui_rmC);
lv_obj_set_width( ui_rmP3, 140);
lv_obj_set_height( ui_rmP3, 30);
lv_obj_set_x( ui_rmP3, -40 );
lv_obj_set_y( ui_rmP3, 0 );
lv_obj_set_align( ui_rmP3, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_rmP3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_rmP3, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_rmP3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_rmP3, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rmT3 = lv_label_create(ui_rmP3);
lv_obj_set_width( ui_rmT3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_rmT3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_rmT3, LV_ALIGN_CENTER );
lv_label_set_text(ui_rmT3,"Master BedRoom");
lv_obj_set_style_text_color(ui_rmT3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_rmT3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_rmT3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_rmT3, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rmPe = lv_obj_create(ui_rmC);
lv_obj_set_width( ui_rmPe, 30);
lv_obj_set_height( ui_rmPe, 30);
lv_obj_set_align( ui_rmPe, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_rmPe, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_rmPe, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_rmPe, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_rmPe, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rmTa = lv_label_create(ui_rmPe);
lv_obj_set_width( ui_rmTa, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_rmTa, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_rmTa, LV_ALIGN_CENTER );
lv_label_set_text(ui_rmTa,"");
lv_obj_set_style_text_color(ui_rmTa, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_rmTa, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_rmTa, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_rmTa, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tdC = lv_obj_create(ui_HAScreen);
lv_obj_remove_style_all(ui_tdC);
lv_obj_set_width( ui_tdC, 280);
lv_obj_set_height( ui_tdC, 120);
lv_obj_set_x( ui_tdC, 30 );
lv_obj_set_y( ui_tdC, 80 );
lv_obj_clear_flag( ui_tdC, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_tdC, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_tdC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_tdC, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_time = lv_textarea_create(ui_tdC);
lv_obj_set_width( ui_time, 150);
lv_obj_set_height( ui_time, 50);
lv_obj_set_x( ui_time, -10 );
lv_obj_set_y( ui_time, 5 );
lv_obj_set_align( ui_time, LV_ALIGN_TOP_RIGHT );
lv_textarea_set_text(ui_time,"00:00");
lv_textarea_set_placeholder_text(ui_time,"Placeholder...");
lv_obj_set_style_text_color(ui_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_time, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_time, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_time, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_temp = lv_textarea_create(ui_tdC);
lv_obj_set_width( ui_temp, 90);
lv_obj_set_height( ui_temp, 50);
lv_obj_set_x( ui_temp, 15 );
lv_obj_set_y( ui_temp, -10 );
lv_obj_set_align( ui_temp, LV_ALIGN_BOTTOM_LEFT );
lv_textarea_set_text(ui_temp,"88°");
lv_textarea_set_placeholder_text(ui_temp,"Placeholder...");
lv_obj_set_style_text_color(ui_temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_temp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_temp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_temp, &lv_font_montserrat_46, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_temp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_loc = lv_textarea_create(ui_tdC);
lv_obj_set_width( ui_loc, 160);
lv_obj_set_height( ui_loc, 20);
lv_obj_set_x( ui_loc, -10 );
lv_obj_set_y( ui_loc, 10 );
lv_obj_set_align( ui_loc, LV_ALIGN_RIGHT_MID );
lv_textarea_set_text(ui_loc,"Hyderabad");
lv_textarea_set_placeholder_text(ui_loc,"Placeholder...");
lv_obj_set_style_text_color(ui_loc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_loc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_loc, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_loc, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_loc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_loc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_cli = lv_textarea_create(ui_tdC);
lv_obj_set_width( ui_cli, 160);
lv_obj_set_height( ui_cli, 25);
lv_obj_set_x( ui_cli, -10 );
lv_obj_set_y( ui_cli, -10 );
lv_obj_set_align( ui_cli, LV_ALIGN_BOTTOM_RIGHT );
lv_textarea_set_text(ui_cli,"Freezing Drizzle");
lv_textarea_set_placeholder_text(ui_cli,"Placeholder...");
lv_obj_set_style_text_color(ui_cli, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_cli, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_cli, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_cli, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_cli, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_cli, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_date = lv_textarea_create(ui_tdC);
lv_obj_set_width( ui_date, 80);
lv_obj_set_height( ui_date, 25);
lv_obj_set_x( ui_date, 15 );
lv_obj_set_y( ui_date, 20 );
lv_textarea_set_text(ui_date,"22 Oct");
lv_textarea_set_placeholder_text(ui_date,"Placeholder...");
lv_obj_set_style_text_color(ui_date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_date, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_date, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_date, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_date, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_stC = lv_obj_create(ui_HAScreen);
lv_obj_remove_style_all(ui_stC);
lv_obj_set_width( ui_stC, 130);
lv_obj_set_height( ui_stC, 120);
lv_obj_set_x( ui_stC, -30 );
lv_obj_set_y( ui_stC, 80 );
lv_obj_set_align( ui_stC, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_stC, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_stC, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_stC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_stC, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifi = lv_textarea_create(ui_stC);
lv_obj_set_width( ui_wifi, 50);
lv_obj_set_height( ui_wifi, 40);
lv_obj_set_x( ui_wifi, -10 );
lv_obj_set_y( ui_wifi, 15 );
lv_obj_set_align( ui_wifi, LV_ALIGN_TOP_RIGHT );
lv_textarea_set_text(ui_wifi,"");
lv_textarea_set_placeholder_text(ui_wifi,"Placeholder...");
lv_obj_set_style_text_color(ui_wifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_wifi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_wifi, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_wifi, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_wifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wifi, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mqtt = lv_textarea_create(ui_stC);
lv_obj_set_width( ui_mqtt, 50);
lv_obj_set_height( ui_mqtt, 40);
lv_obj_set_x( ui_mqtt, 10 );
lv_obj_set_y( ui_mqtt, 15 );
lv_textarea_set_text(ui_mqtt,"");
lv_textarea_set_placeholder_text(ui_mqtt,"Placeholder...");
lv_obj_set_style_text_color(ui_mqtt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mqtt, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_mqtt, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_mqtt, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_mqtt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mqtt, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batt = lv_textarea_create(ui_stC);
lv_obj_set_width( ui_batt, 50);
lv_obj_set_height( ui_batt, 40);
lv_obj_set_x( ui_batt, 10 );
lv_obj_set_y( ui_batt, -10 );
lv_obj_set_align( ui_batt, LV_ALIGN_BOTTOM_LEFT );
lv_textarea_set_text(ui_batt,"");
lv_textarea_set_placeholder_text(ui_batt,"Placeholder...");
lv_obj_set_style_text_color(ui_batt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_batt, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_batt, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_batt, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_batt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batt, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bell = lv_textarea_create(ui_stC);
lv_obj_set_width( ui_bell, 50);
lv_obj_set_height( ui_bell, 40);
lv_obj_set_x( ui_bell, -10 );
lv_obj_set_y( ui_bell, -10 );
lv_obj_set_align( ui_bell, LV_ALIGN_BOTTOM_RIGHT );
lv_textarea_set_text(ui_bell,"");
lv_textarea_set_placeholder_text(ui_bell,"Placeholder...");
lv_obj_set_style_text_color(ui_bell, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_bell, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_bell, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_bell, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_bell, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_bell, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_haswCnd = lv_obj_create(ui_HAScreen);
lv_obj_remove_style_all(ui_haswCnd);
lv_obj_set_width( ui_haswCnd, 420);
lv_obj_set_height( ui_haswCnd, 230);
lv_obj_set_x( ui_haswCnd, 0 );
lv_obj_set_y( ui_haswCnd, -35 );
lv_obj_set_align( ui_haswCnd, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_haswCnd, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_haswCnd, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_haswCnd, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_haswCnd, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_haswCnd, 100, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_noData = lv_textarea_create(ui_haswCnd);
lv_obj_set_width( ui_noData, 300);
lv_obj_set_height( ui_noData, 50);
lv_obj_set_align( ui_noData, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_noData,"No elements data received from HomeAssistant");
lv_textarea_set_placeholder_text(ui_noData,"Placeholder...");
lv_obj_set_style_text_color(ui_noData, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_noData, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_noData, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_noData, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_noData, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_noData, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_haswC = lv_obj_create(ui_HAScreen);
lv_obj_remove_style_all(ui_haswC);
lv_obj_set_width( ui_haswC, 420);
lv_obj_set_height( ui_haswC, 230);
lv_obj_set_x( ui_haswC, 0 );
lv_obj_set_y( ui_haswC, -35 );
lv_obj_set_align( ui_haswC, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_haswC, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_sw1 = lv_obj_create(ui_haswC);
lv_obj_remove_style_all(ui_sw1);
lv_obj_set_width( ui_sw1, 205);
lv_obj_set_height( ui_sw1, 70);
lv_obj_set_x( ui_sw1, 1 );
lv_obj_set_y( ui_sw1, 1 );
lv_obj_clear_flag( ui_sw1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_sw1, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_sw1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_sw1, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_icc1 = lv_obj_create(ui_sw1);
lv_obj_remove_style_all(ui_icc1);
lv_obj_set_width( ui_icc1, 50);
lv_obj_set_height( ui_icc1, 50);
lv_obj_set_x( ui_icc1, 10 );
lv_obj_set_y( ui_icc1, 0 );
lv_obj_set_align( ui_icc1, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_icc1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_icc1, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_icc1, lv_color_hex(0xFEC106), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_icc1, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_icp1 = lv_obj_create(ui_icc1);
lv_obj_set_width( ui_icp1, 32);
lv_obj_set_height( ui_icp1, 32);
lv_obj_set_align( ui_icp1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_icp1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_icp1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_icp1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_icp1, &ui_img_253037777, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_recolor(ui_icp1, lv_color_hex(0xFEC106), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_icp1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_swn1 = lv_textarea_create(ui_sw1);
lv_obj_set_width( ui_swn1, 125);
lv_obj_set_height( ui_swn1, 20);
lv_obj_set_x( ui_swn1, -10 );
lv_obj_set_y( ui_swn1, -5 );
lv_obj_set_align( ui_swn1, LV_ALIGN_RIGHT_MID );
lv_textarea_set_text(ui_swn1,"Lights");
lv_textarea_set_placeholder_text(ui_swn1,"Placeholder...");
lv_obj_set_style_text_color(ui_swn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_swn1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_swn1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_swn1, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_swn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_swn1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rm1 = lv_textarea_create(ui_sw1);
lv_obj_set_width( ui_rm1, 125);
lv_obj_set_height( ui_rm1, 16);
lv_obj_set_x( ui_rm1, -10 );
lv_obj_set_y( ui_rm1, -14 );
lv_obj_set_align( ui_rm1, LV_ALIGN_BOTTOM_RIGHT );
lv_textarea_set_text(ui_rm1,"Master BedRoom");
lv_textarea_set_placeholder_text(ui_rm1,"Placeholder...");
lv_obj_set_style_text_color(ui_rm1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_rm1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_rm1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_rm1, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_rm1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_rm1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_sw2 = lv_obj_create(ui_haswC);
lv_obj_remove_style_all(ui_sw2);
lv_obj_set_width( ui_sw2, 205);
lv_obj_set_height( ui_sw2, 70);
lv_obj_set_x( ui_sw2, 1 );
lv_obj_set_y( ui_sw2, 1 );
lv_obj_set_align( ui_sw2, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_sw2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_sw2, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_sw2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_sw2, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_icc2 = lv_obj_create(ui_sw2);
lv_obj_remove_style_all(ui_icc2);
lv_obj_set_width( ui_icc2, 50);
lv_obj_set_height( ui_icc2, 50);
lv_obj_set_x( ui_icc2, 10 );
lv_obj_set_y( ui_icc2, 0 );
lv_obj_set_align( ui_icc2, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_icc2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_icc2, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_icc2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_icc2, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_icp2 = lv_obj_create(ui_icc2);
lv_obj_set_width( ui_icp2, 32);
lv_obj_set_height( ui_icp2, 32);
lv_obj_set_align( ui_icp2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_icp2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_icp2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_icp2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_icp2, &ui_img_133537992, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_recolor(ui_icp2, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_icp2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_swn2 = lv_textarea_create(ui_sw2);
lv_obj_set_width( ui_swn2, 125);
lv_obj_set_height( ui_swn2, 20);
lv_obj_set_x( ui_swn2, -10 );
lv_obj_set_y( ui_swn2, -5 );
lv_obj_set_align( ui_swn2, LV_ALIGN_RIGHT_MID );
lv_textarea_set_text(ui_swn2,"Air Conditioner");
lv_textarea_set_placeholder_text(ui_swn2,"Placeholder...");
lv_obj_set_style_text_color(ui_swn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_swn2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_swn2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_swn2, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_swn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_swn2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rm2 = lv_textarea_create(ui_sw2);
lv_obj_set_width( ui_rm2, 125);
lv_obj_set_height( ui_rm2, 16);
lv_obj_set_x( ui_rm2, -10 );
lv_obj_set_y( ui_rm2, -14 );
lv_obj_set_align( ui_rm2, LV_ALIGN_BOTTOM_RIGHT );
lv_textarea_set_text(ui_rm2,"Children BedRoom");
lv_textarea_set_placeholder_text(ui_rm2,"Placeholder...");
lv_obj_set_style_text_color(ui_rm2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_rm2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_rm2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_rm2, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_rm2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_rm2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_sw3 = lv_obj_create(ui_haswC);
lv_obj_remove_style_all(ui_sw3);
lv_obj_set_width( ui_sw3, 205);
lv_obj_set_height( ui_sw3, 70);
lv_obj_set_x( ui_sw3, 1 );
lv_obj_set_y( ui_sw3, 1 );
lv_obj_set_align( ui_sw3, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_sw3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_sw3, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_sw3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_sw3, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_icc3 = lv_obj_create(ui_sw3);
lv_obj_remove_style_all(ui_icc3);
lv_obj_set_width( ui_icc3, 50);
lv_obj_set_height( ui_icc3, 50);
lv_obj_set_x( ui_icc3, 10 );
lv_obj_set_y( ui_icc3, 0 );
lv_obj_set_align( ui_icc3, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_icc3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_icc3, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_icc3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_icc3, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_icp3 = lv_obj_create(ui_icc3);
lv_obj_set_width( ui_icp3, 32);
lv_obj_set_height( ui_icp3, 32);
lv_obj_set_align( ui_icp3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_icp3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_icp3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_icp3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_icp3, &ui_img_1332138075, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_recolor(ui_icp3, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_icp3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_swn3 = lv_textarea_create(ui_sw3);
lv_obj_set_width( ui_swn3, 125);
lv_obj_set_height( ui_swn3, 20);
lv_obj_set_x( ui_swn3, -10 );
lv_obj_set_y( ui_swn3, -5 );
lv_obj_set_align( ui_swn3, LV_ALIGN_RIGHT_MID );
lv_textarea_set_text(ui_swn3,"Fan");
lv_textarea_set_placeholder_text(ui_swn3,"Placeholder...");
lv_obj_set_style_text_color(ui_swn3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_swn3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_swn3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_swn3, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_swn3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_swn3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rm3 = lv_textarea_create(ui_sw3);
lv_obj_set_width( ui_rm3, 125);
lv_obj_set_height( ui_rm3, 16);
lv_obj_set_x( ui_rm3, -10 );
lv_obj_set_y( ui_rm3, -14 );
lv_obj_set_align( ui_rm3, LV_ALIGN_BOTTOM_RIGHT );
lv_textarea_set_text(ui_rm3,"Dining Room");
lv_textarea_set_placeholder_text(ui_rm3,"Placeholder...");
lv_obj_set_style_text_color(ui_rm3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_rm3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_rm3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_rm3, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_rm3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_rm3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_sw4 = lv_obj_create(ui_haswC);
lv_obj_remove_style_all(ui_sw4);
lv_obj_set_width( ui_sw4, 205);
lv_obj_set_height( ui_sw4, 70);
lv_obj_set_x( ui_sw4, 1 );
lv_obj_set_y( ui_sw4, 1 );
lv_obj_set_align( ui_sw4, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_sw4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_sw4, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_sw4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_sw4, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_icc4 = lv_obj_create(ui_sw4);
lv_obj_remove_style_all(ui_icc4);
lv_obj_set_width( ui_icc4, 50);
lv_obj_set_height( ui_icc4, 50);
lv_obj_set_x( ui_icc4, 10 );
lv_obj_set_y( ui_icc4, 0 );
lv_obj_set_align( ui_icc4, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_icc4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_icc4, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_icc4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_icc4, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_icp4 = lv_obj_create(ui_icc4);
lv_obj_set_width( ui_icp4, 32);
lv_obj_set_height( ui_icp4, 32);
lv_obj_set_align( ui_icp4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_icp4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_icp4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_icp4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_icp4, &ui_img_435491338, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_recolor(ui_icp4, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_icp4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_swn4 = lv_textarea_create(ui_sw4);
lv_obj_set_width( ui_swn4, 125);
lv_obj_set_height( ui_swn4, 20);
lv_obj_set_x( ui_swn4, -10 );
lv_obj_set_y( ui_swn4, -5 );
lv_obj_set_align( ui_swn4, LV_ALIGN_RIGHT_MID );
lv_textarea_set_text(ui_swn4,"TV");
lv_textarea_set_placeholder_text(ui_swn4,"Placeholder...");
lv_obj_set_style_text_color(ui_swn4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_swn4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_swn4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_swn4, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_swn4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_swn4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rm4 = lv_textarea_create(ui_sw4);
lv_obj_set_width( ui_rm4, 125);
lv_obj_set_height( ui_rm4, 16);
lv_obj_set_x( ui_rm4, -10 );
lv_obj_set_y( ui_rm4, -14 );
lv_obj_set_align( ui_rm4, LV_ALIGN_BOTTOM_RIGHT );
lv_textarea_set_text(ui_rm4,"Living Room");
lv_textarea_set_placeholder_text(ui_rm4,"Placeholder...");
lv_obj_set_style_text_color(ui_rm4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_rm4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_rm4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_rm4, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_rm4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_rm4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_sw5 = lv_obj_create(ui_haswC);
lv_obj_remove_style_all(ui_sw5);
lv_obj_set_width( ui_sw5, 205);
lv_obj_set_height( ui_sw5, 70);
lv_obj_set_x( ui_sw5, 1 );
lv_obj_set_y( ui_sw5, 1 );
lv_obj_set_align( ui_sw5, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_sw5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_sw5, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_sw5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_sw5, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_icc5 = lv_obj_create(ui_sw5);
lv_obj_remove_style_all(ui_icc5);
lv_obj_set_width( ui_icc5, 50);
lv_obj_set_height( ui_icc5, 50);
lv_obj_set_x( ui_icc5, 10 );
lv_obj_set_y( ui_icc5, 0 );
lv_obj_set_align( ui_icc5, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_icc5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_icc5, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_icc5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_icc5, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_icp5 = lv_obj_create(ui_icc5);
lv_obj_set_width( ui_icp5, 32);
lv_obj_set_height( ui_icp5, 32);
lv_obj_set_align( ui_icp5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_icp5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_icp5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_icp5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_icp5, &ui_img_252433816, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_recolor(ui_icp5, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_icp5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_swn5 = lv_textarea_create(ui_sw5);
lv_obj_set_width( ui_swn5, 125);
lv_obj_set_height( ui_swn5, 20);
lv_obj_set_x( ui_swn5, -10 );
lv_obj_set_y( ui_swn5, -5 );
lv_obj_set_align( ui_swn5, LV_ALIGN_RIGHT_MID );
lv_textarea_set_text(ui_swn5,"Switch");
lv_textarea_set_placeholder_text(ui_swn5,"Placeholder...");
lv_obj_set_style_text_color(ui_swn5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_swn5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_swn5, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_swn5, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_swn5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_swn5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rm5 = lv_textarea_create(ui_sw5);
lv_obj_set_width( ui_rm5, 125);
lv_obj_set_height( ui_rm5, 16);
lv_obj_set_x( ui_rm5, -10 );
lv_obj_set_y( ui_rm5, -14 );
lv_obj_set_align( ui_rm5, LV_ALIGN_BOTTOM_RIGHT );
lv_textarea_set_text(ui_rm5,"Kitchen");
lv_textarea_set_placeholder_text(ui_rm5,"Placeholder...");
lv_obj_set_style_text_color(ui_rm5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_rm5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_rm5, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_rm5, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_rm5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_rm5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_sw6 = lv_obj_create(ui_haswC);
lv_obj_remove_style_all(ui_sw6);
lv_obj_set_width( ui_sw6, 205);
lv_obj_set_height( ui_sw6, 70);
lv_obj_set_x( ui_sw6, 1 );
lv_obj_set_y( ui_sw6, 1 );
lv_obj_set_align( ui_sw6, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_clear_flag( ui_sw6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_sw6, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_sw6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_sw6, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_icc6 = lv_obj_create(ui_sw6);
lv_obj_remove_style_all(ui_icc6);
lv_obj_set_width( ui_icc6, 50);
lv_obj_set_height( ui_icc6, 50);
lv_obj_set_x( ui_icc6, 10 );
lv_obj_set_y( ui_icc6, 0 );
lv_obj_set_align( ui_icc6, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_icc6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_icc6, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_icc6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_icc6, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_icp6 = lv_obj_create(ui_icc6);
lv_obj_set_width( ui_icp6, 32);
lv_obj_set_height( ui_icp6, 32);
lv_obj_set_align( ui_icp6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_icp6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_icp6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_icp6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_icp6, &ui_img_1965837174, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_recolor(ui_icp6, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_icp6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_swn6 = lv_textarea_create(ui_sw6);
lv_obj_set_width( ui_swn6, 125);
lv_obj_set_height( ui_swn6, 20);
lv_obj_set_x( ui_swn6, -10 );
lv_obj_set_y( ui_swn6, -5 );
lv_obj_set_align( ui_swn6, LV_ALIGN_RIGHT_MID );
lv_textarea_set_text(ui_swn6,"Washer");
lv_textarea_set_placeholder_text(ui_swn6,"Placeholder...");
lv_obj_set_style_text_color(ui_swn6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_swn6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_swn6, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_swn6, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_swn6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_swn6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rm6 = lv_textarea_create(ui_sw6);
lv_obj_set_width( ui_rm6, 125);
lv_obj_set_height( ui_rm6, 16);
lv_obj_set_x( ui_rm6, -10 );
lv_obj_set_y( ui_rm6, -14 );
lv_obj_set_align( ui_rm6, LV_ALIGN_BOTTOM_RIGHT );
lv_textarea_set_text(ui_rm6,"Utility");
lv_textarea_set_placeholder_text(ui_rm6,"Placeholder...");
lv_obj_set_style_text_color(ui_rm6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_rm6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_rm6, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_rm6, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_rm6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_rm6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_HAScreen_screen_destroy(void)
{
   if (ui_HAScreen) lv_obj_del(ui_HAScreen);

// NULL screen variables
ui_HAScreen= NULL;
ui_baseP= NULL;
ui_topP= NULL;
ui_rmC= NULL;
ui_rmP1= NULL;
ui_rmT1= NULL;
ui_rmP2= NULL;
ui_rmT2= NULL;
ui_rmP3= NULL;
ui_rmT3= NULL;
ui_rmPe= NULL;
ui_rmTa= NULL;
ui_tdC= NULL;
ui_time= NULL;
ui_temp= NULL;
ui_loc= NULL;
ui_cli= NULL;
ui_date= NULL;
ui_stC= NULL;
ui_wifi= NULL;
ui_mqtt= NULL;
ui_batt= NULL;
ui_bell= NULL;
ui_haswCnd= NULL;
ui_noData= NULL;
ui_haswC= NULL;
ui_sw1= NULL;
ui_icc1= NULL;
ui_icp1= NULL;
ui_swn1= NULL;
ui_rm1= NULL;
ui_sw2= NULL;
ui_icc2= NULL;
ui_icp2= NULL;
ui_swn2= NULL;
ui_rm2= NULL;
ui_sw3= NULL;
ui_icc3= NULL;
ui_icp3= NULL;
ui_swn3= NULL;
ui_rm3= NULL;
ui_sw4= NULL;
ui_icc4= NULL;
ui_icp4= NULL;
ui_swn4= NULL;
ui_rm4= NULL;
ui_sw5= NULL;
ui_icc5= NULL;
ui_icp5= NULL;
ui_swn5= NULL;
ui_rm5= NULL;
ui_sw6= NULL;
ui_icc6= NULL;
ui_icp6= NULL;
ui_swn6= NULL;
ui_rm6= NULL;

}
