// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT CompRoom

lv_obj_t *ui_CompRoom_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_CompRoom;
cui_CompRoom = lv_obj_create(comp_parent);
lv_obj_set_height( cui_CompRoom, 30);
lv_obj_set_width( cui_CompRoom, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( cui_CompRoom, LV_ALIGN_LEFT_MID );
lv_obj_add_state( cui_CompRoom, LV_STATE_CHECKED );     /// States
lv_obj_remove_flag( cui_CompRoom, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_CompRoom, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_CompRoom, lv_color_hex(0x28A0FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_CompRoom, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_CompRoom, lv_color_hex(0x28A0FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_CompRoom, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_CompRoom, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_CompRoom, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_CompRoom, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_CompRoom, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(cui_CompRoom, 24, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(cui_CompRoom, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(cui_CompRoom, 80, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_color(cui_CompRoom, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(cui_CompRoom, 80, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_pad_left(cui_CompRoom, 10, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_pad_right(cui_CompRoom, 10, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_pad_top(cui_CompRoom, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_pad_bottom(cui_CompRoom, 0, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_t *cui_rmT1;
cui_rmT1 = lv_label_create(cui_CompRoom);
lv_obj_set_width( cui_rmT1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_rmT1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_rmT1, LV_ALIGN_CENTER );
lv_label_set_text(cui_rmT1,"My Home");
lv_obj_set_style_text_color(cui_rmT1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_rmT1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(cui_rmT1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_rmT1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_COMPROOM_NUM);
children[UI_COMP_COMPROOM_COMPROOM] = cui_CompRoom;
children[UI_COMP_COMPROOM_RMT1] = cui_rmT1;
lv_obj_add_event_cb(cui_CompRoom, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_CompRoom, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_CompRoom_create_hook(cui_CompRoom);
return cui_CompRoom; 
}

