// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _UI_COMP_COMPROOM_H
#define _UI_COMP_COMPROOM_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT CompRoom
#define UI_COMP_COMPROOM_COMPROOM 0
#define UI_COMP_COMPROOM_RMT1 1
#define _UI_COMP_COMPROOM_NUM 2
lv_obj_t *ui_CompRoom_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
