// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _UI_COMP_COMPSWITCH_H
#define _UI_COMP_COMPSWITCH_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT CompSwitch
#define UI_COMP_COMPSWITCH_COMPSWITCH 0
#define UI_COMP_COMPSWITCH_ICC1 1
#define UI_COMP_COMPSWITCH_ICC1_ICP1 2
#define UI_COMP_COMPSWITCH_SWN1 3
#define UI_COMP_COMPSWITCH_RM1 4
#define _UI_COMP_COMPSWITCH_NUM 5
lv_obj_t *ui_CompSwitch_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
