// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SLEEPSCREEN_H
#define UI_SLEEPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SleepScreen
extern void ui_SleepScreen_screen_init(void);
extern void ui_SleepScreen_screen_destroy(void);
extern lv_obj_t *ui_SleepScreen;
extern lv_obj_t *ui_ImgBg;
extern lv_obj_t *ui_IconWeather;
extern lv_obj_t *ui_LabelDate;
extern lv_obj_t *ui_LabelTime;
extern lv_obj_t *ui_LabelCity;
extern lv_obj_t *ui_AlertsLabel;
extern lv_obj_t *ui_LabelTemp;
extern lv_obj_t *ui_LabelWeather;
extern lv_obj_t *ui_IconMqtt;
extern lv_obj_t *ui_IconWifi;
extern lv_obj_t *ui_IconBat;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

